services:
 webserver:
    build: .
    container_name: painelconflitos-api
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./codigo-fonte:/var/www/html
      - ./docker/apache2/logs:/var/log/apache2
    environment:
      - DB_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"