apiVersion: v1
kind: Service
metadata:
  name: paineldeconflitos-app-service  # Nome do serviço
spec:
  selector:
    app: paineldeconflitos-app  # Deve bater com o rótulo do deployment
  ports:
  - protocol: TCP
    port: 80        # Porta do serviço
    targetPort: 80  # Porta do pod
  type: ClusterIP   # Padrão (só acessível dentro do cluster)